[changelog]
header = "# Changelog\n\n"
body = """
{% if version -%}
## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## Unreleased
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message }}
{% endfor %}
{% endfor %}

"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
commit_preprocessors = [
  { pattern = "^\\s+", replace = "" },
]
commit_parsers = [
  { message = "(?i)^\\s*feat", group = "Added" },
  { message = "(?i)^\\s*fix", group = "Fixed" },
  { message = "(?i)^\\s*docs", group = "Docs" },
  { message = "(?i)^\\s*refactor", group = "Changed" },
  { message = "(?i)^\\s*style", group = "Changed" },
  { message = "(?i)^\\s*test", group = "Changed" },
  { message = "(?i)^\\s*chore", group = "Changed" },
]
tag_pattern = "v[0-9].*"
sort_commits = "newest"
